import java.io.BufferedWriter;   // Allows writing data to a file efficiently
import java.io.FileWriter;       // Enables appending new employee data to the CSV
import java.io.PrintWriter;      // Used to format and write data to the CSV file
import javax.swing.JOptionPane;  // Displays error and success messages to the user
import java.io.File;             // Represents the employee CSV file
import java.io.BufferedReader;   // Reads data from the CSV file
import java.io.FileReader;       // Reads file contents line by line
import java.io.IOException;      // Handles file-related errors (reading/writing issues)
import java.util.ArrayList;      // Provides dynamic lists that allow easy data manipulation

/**
 * `AddEmployee` class allows users to add new employee records.
 * It ensures Employee Numbers auto-increment and prevents manual edits.
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Constructor - Initializes the AddEmployee form.
     * Calls `generateNextEmpNum()` to auto-set the Employee Number.
     */
    public AddEmployee() {
        initComponents(); // Initializes UI components
        generateNextEmpNum(); // Auto-set Employee Number when the form opens

        // Ensure Employee Number field is uneditable and visually locked
        jTxtEmpNum.setEditable(false); // Prevent typing
        jTxtEmpNum.setFocusable(false); // Prevent cursor focus (extra safeguard)
        jTxtEmpNum.setBackground(java.awt.Color.LIGHT_GRAY); // Gray out for clarity
    }
    
    /**
     * Reads the last Employee Number from the CSV file and increments it by 1.
     * Ensures a new Employee Number is assigned automatically.
     */
    private void generateNextEmpNum() {
        try {
            File inputFile = new File("src/data/employee_info.csv"); // Locate CSV file
            BufferedReader reader = new BufferedReader(new FileReader(inputFile)); // Read the file
            
            String lastLine = "", line;
            while ((line = reader.readLine()) != null) {
                lastLine = line; // Store last valid employee entry
            }
            reader.close(); // Close file reader after reading

            // Extract last Employee Number and increment it
            int newEmpNum = 10001; // Default if CSV is empty
            if (!lastLine.isEmpty()) {
                String[] data = lastLine.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)"); // Correctly split CSV data
                if (data.length > 0) {
                    newEmpNum = Integer.parseInt(data[0].trim()) + 1; // Auto-increment Employee ID
                }
            }

            // Set the new Employee Number and disable manual editing
            jTxtEmpNum.setText(String.valueOf(newEmpNum));
            jTxtEmpNum.setEditable(false); // Prevent manual edits

        } catch (IOException e) {
            e.printStackTrace(); // Print error details for debugging
            JOptionPane.showMessageDialog(this, "Error generating Employee Number!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextPAGIBIG = new javax.swing.JTextField();
        jLabelAddEmp = new javax.swing.JLabel();
        jTextPHILHEALTH = new javax.swing.JTextField();
        jLblEmpNum = new javax.swing.JLabel();
        jTextTIN = new javax.swing.JTextField();
        jLblLastName = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLblFirstName = new javax.swing.JLabel();
        jLblPhoneNumber = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jLblPosition = new javax.swing.JLabel();
        jTxtEmpNum = new javax.swing.JTextField();
        jTxtLastName = new javax.swing.JTextField();
        jTxtFirstName = new javax.swing.JTextField();
        jTxtPhoneNumber = new javax.swing.JTextField();
        jTxtStatus = new javax.swing.JTextField();
        jTxtPosition = new javax.swing.JTextField();
        jLblSSS = new javax.swing.JLabel();
        jLblPAGIBIG = new javax.swing.JLabel();
        jLblPHILHEALTH = new javax.swing.JLabel();
        jLblTIN = new javax.swing.JLabel();
        jTextSSS = new javax.swing.JTextField();
        jLblPersonal = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabelAddEmp.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelAddEmp.setText("Add New Employee");

        jLblEmpNum.setText("Employee Number:");

        jLblLastName.setText("Last Name:");

        jButtonSubmit.setText("Submit");
        jButtonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLblFirstName.setText("First Name:");

        jLblPhoneNumber.setText("Phone Number:");

        jLblStatus.setText("Status:");

        jLblPosition.setText("Position:");

        jTxtEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpNumActionPerformed(evt);
            }
        });

        jLblSSS.setText("SSS");

        jLblPAGIBIG.setText("PAGIBIG");

        jLblPHILHEALTH.setText("PHILEALTH");

        jLblTIN.setText("TIN");

        jTextSSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSSSActionPerformed(evt);
            }
        });

        jLblPersonal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPersonal.setText("Personal Information");

        jButtonCancel.setText("Close");
        jButtonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblPHILHEALTH, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtEmpNum, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(jTxtLastName)
                                .addComponent(jTxtFirstName)
                                .addComponent(jTxtPhoneNumber)
                                .addComponent(jTxtStatus)
                                .addComponent(jTxtPosition)
                                .addComponent(jTextSSS)
                                .addComponent(jTextPAGIBIG)
                                .addComponent(jTextPHILHEALTH))
                            .addComponent(jTextTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLblPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelAddEmp)
                .addGap(32, 32, 32)
                .addComponent(jLblPersonal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmpNum)
                    .addComponent(jTxtEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblLastName)
                    .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblFirstName)
                    .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPhoneNumber)
                    .addComponent(jTxtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblStatus)
                    .addComponent(jTxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPosition)
                    .addComponent(jTxtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSSS)
                    .addComponent(jTextSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPAGIBIG)
                    .addComponent(jTextPAGIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblPHILHEALTH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblTIN)
                            .addComponent(jTextTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextPHILHEALTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmpNumActionPerformed

    private void jTextSSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSSSActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
    // Handles adding a new employee when the "Submit" button is clicked

    // Retrieve employee details from form input fields
    String lastName = jTxtLastName.getText().trim();
    String firstName = jTxtFirstName.getText().trim();
    String phoneNumber = jTxtPhoneNumber.getText().trim();
    String status = jTxtStatus.getText().trim();
    String position = jTxtPosition.getText().trim();
    String sss = jTextSSS.getText().trim();
    String pagibig = jTextPAGIBIG.getText().trim();
    String philhealth = jTextPHILHEALTH.getText().trim();
    String tin = jTextTIN.getText().trim();
    String supervisor = "NA"; // Adjust this for actual supervisor input

    // Validate required fields before saving
    if (lastName.isEmpty() || firstName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last Name and First Name are required!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Load all employee records into an ArrayList for efficient modifications
    ArrayList<String> employeeRecords = new ArrayList<>();
    int newEmpNum = 10001; // Default if CSV is empty
    try (BufferedReader reader = new BufferedReader(new FileReader("src/data/employee_info.csv"))) {
        String line;
        while ((line = reader.readLine()) != null) {
            employeeRecords.add(line); // Store each employee record in memory
        }

        // Get the last Employee Number and auto-increment it
        if (!employeeRecords.isEmpty()) {
            String lastLine = employeeRecords.get(employeeRecords.size() - 1); // Get last entry
            String[] lastData = lastLine.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");
            newEmpNum = Integer.parseInt(lastData[0].trim()) + 1;
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading employee data!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create the new employee entry
    String newEmployeeEntry = String.join(",", 
        String.valueOf(newEmpNum), lastName, firstName, phoneNumber, status, position, supervisor, sss, pagibig, philhealth, tin
    );

    // Add the new employee entry to the list
    employeeRecords.add(newEmployeeEntry);

    // Write the updated employee records back to the CSV file in a single operation
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("src/data/employee_info.csv"))) {
        for (String record : employeeRecords) {
            writer.write(record + "\n"); // Write each updated record to the file
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving employee data!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this, "Employee added successfully!");

    // Refresh the table view to reflect new entries
    if (EmployeeTable.getInstance() != null) {
        EmployeeTable.getInstance().refreshEmployeeTable(); 
    }

    // Close the form after successful submission
    dispose();

    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    dispose(); 
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAddEmp;
    private javax.swing.JLabel jLblEmpNum;
    private javax.swing.JLabel jLblFirstName;
    private javax.swing.JLabel jLblLastName;
    private javax.swing.JLabel jLblPAGIBIG;
    private javax.swing.JLabel jLblPHILHEALTH;
    private javax.swing.JLabel jLblPersonal;
    private javax.swing.JLabel jLblPhoneNumber;
    private javax.swing.JLabel jLblPosition;
    private javax.swing.JLabel jLblSSS;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextPAGIBIG;
    private javax.swing.JTextField jTextPHILHEALTH;
    private javax.swing.JTextField jTextSSS;
    private javax.swing.JTextField jTextTIN;
    private javax.swing.JTextField jTxtEmpNum;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtPhoneNumber;
    private javax.swing.JTextField jTxtPosition;
    private javax.swing.JTextField jTxtStatus;
    // End of variables declaration//GEN-END:variables
}
